// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyyqtjvwbbktwlxgnkzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5eXF0anZ3YmJrdHdseGdua3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NjI1MjIsImV4cCI6MjA4ODEzODUyMn0.O6sLUeaAiHiRWMxQlwO86g2skIIvzLbUmD1DhoESVLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});